### ISSUE TITLE
README File Has No Installation Instructions

### ISSUE THREAD

**Issue by DarioS** [raphael-group/THetA#11]
The README file should explain how to install the software. It mentions a `bin` directory but after extracting the archive I see no such folder, so I guess the code needs to be compiled.

**Comment by gsatas** [comment]
The instructions for how to compile the code, along with system
requirements, are contained in the manual in doc/MANUAL.txt. The README
file makes reference to this in the following line.


"Manual; MANUAL.txt - A complete description of how to install/run the
software."
