### ISSUE TITLE
Support for UCSC Style Chromosome IDs

### ISSUE THREAD

**Issue by DarioS** [raphael-group/THetA#12]
```
                       ...
	2. chromosome number (Integer) - chromosome on which the interval
	   occurs
                       ...
```

This seems unnecessarily restrictive and creates extra work for the end user. Why not allow values like chr1 and chrM ? I've seen other bioinformatics Python packages with this unusual limitation, too.

**Comment by gsatas** [comment]
Thank you for bringing this to our attention. The code already accepted chrmN format and we updated the code to accept chrN format. The manual has been updated the manual to describe allowed formats.
