### ISSUE TITLE
LICENSE has unicode character

### ISSUE THREAD

**Issue by drmjc** [raphael-group/THetA#13]
Hi,
The new license in the header of the python files has a '\xe2' character, which is preventing me from running the code: `/opt/THetA/bin/RunTHetA`                                                    

> Traceback (most recent call last):
>   File "/opt/THetA/bin/../python/RunTHetA.py", line 38, in <module>
>     from SelectIntervals import *
>   File "/opt/THetA/python/SelectIntervals.py", line 23
> SyntaxError: Non-ASCII character '\xe2' in file /opt/THetA/python/SelectIntervals.py on line 23, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
> 

This solution seems to work: add this to the first 2 lines of each file:

    #!/usr/bin/env python
    # -*- coding: utf-8 -*-

cheers,
Mark

**Comment by gsatas** [comment]
Hi Mark,

Thanks for bringing this to our attention. I've updated the license in the python files to not contain unicode characters. 

Gryte
