### ISSUE TITLE
BAF?

### ISSUE THREAD

**Issue by SooLee** [raphael-group/THetA#6]
Hello,

Thanks for the program. Just a quick question. Does THetA 0.6 take BAF as input? I might be missing it from MANUAL.txt - the input format doesn't seem to contain BAF information. (I got an impression from the paper that THetA2 uses BAF as well as read depths.) Thanks in advance!

S.

**Comment by gsatas** [comment]
Hello, thanks for your interest in THetA. The current release of THetA doesn't take BAFs as input, but we provide a post-processing script that uses BAF to choose between multiple THetA solutions.  This script is runBAFGaussianModel and is described in the manual in section 9. We are also working on a version that will take BAFs directly as input and this will be released in the coming weeks.

**Comment by SooLee** [comment]
Thanks for your answer. My MANUAL doesn't have section 9, though. Is it a part of the current release?

**Comment by SooLee** [comment]
Would you be willing to release another version based on the current codes? It seems that have been many updates since the latest release and I see that section 9 is among those updates. Thanks.

**Comment by gsatas** [comment]
It looks like version 0.62 includes the BAF code, which is currently in the repository. As mentioned, we're in the process of putting together a new major release, which will be available soon.

**Comment by SooLee** [comment]
Ok, thanks.
